/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen3mariorodriguez;

import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class Inventario extends javax.swing.JFrame {
    
    DefaultTableModel tabla = new DefaultTableModel();
    boolean activo = false;

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        this.setTitle("Inventario");
        String[] columnas = new String[]{"CODIGO", "DESCRIPCION", "CANTIDAD", "TIPO", "ACTIVO", "PRECIO"};
        tabla.setColumnIdentifiers(columnas);
        Tacontrol.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Tcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tdescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tcantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Rsi = new javax.swing.JRadioButton();
        Rno = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Tprecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tacontrol = new javax.swing.JTable();
        Bagregar = new javax.swing.JButton();
        Bborrar = new javax.swing.JButton();
        Bmodificar = new javax.swing.JButton();
        Breporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CONTROL DE INVENTARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 320, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mario\\OneDrive\\Escritorio\\INVENTARIO2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 20, 90, 72);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(17, 17, 50, 16);
        jPanel1.add(Tcodigo);
        Tcodigo.setBounds(73, 14, 90, 22);

        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(199, 17, 74, 16);
        jPanel1.add(Tdescripcion);
        Tdescripcion.setBounds(279, 14, 150, 22);

        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(17, 76, 61, 16);
        jPanel1.add(Tcantidad);
        Tcantidad.setBounds(84, 70, 64, 22);

        jLabel6.setText("TIPO:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(173, 48, 60, 16);

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desechable", "Comestible", "Abarrote", "Ropa" }));
        jPanel1.add(Combo);
        Combo.setBounds(173, 70, 94, 22);

        jLabel7.setText("ACTIVO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(285, 48, 70, 16);

        buttonGroup1.add(Rsi);
        Rsi.setText("SI");
        jPanel1.add(Rsi);
        Rsi.setBounds(285, 71, 53, 21);

        buttonGroup1.add(Rno);
        Rno.setText("NO");
        jPanel1.add(Rno);
        Rno.setBounds(344, 71, 60, 21);

        jLabel8.setText("PRECIO");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 50, 50, 16);
        jPanel1.add(Tprecio);
        Tprecio.setBounds(420, 70, 90, 22);

        Tacontrol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tacontrol);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 430, 100);

        Bagregar.setText("Agregar");
        Bagregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarActionPerformed(evt);
            }
        });
        jPanel1.add(Bagregar);
        Bagregar.setBounds(30, 230, 70, 22);

        Bborrar.setText("Borrar");
        Bborrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });
        jPanel1.add(Bborrar);
        Bborrar.setBounds(140, 230, 70, 22);

        Bmodificar.setText("Modificar");
        Bmodificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(Bmodificar);
        Bmodificar.setBounds(250, 230, 80, 22);

        Breporte.setText("Reporte");
        Breporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Breporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreporteActionPerformed(evt);
            }
        });
        jPanel1.add(Breporte);
        Breporte.setBounds(360, 230, 90, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 100, 550, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarActionPerformed
        ConsultaActivo();
        Agregar();
        Guardar();
    }//GEN-LAST:event_BagregarActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        Borrar();
    }//GEN-LAST:event_BborrarActionPerformed

    private void BmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarActionPerformed
        Modificar();
        Tcodigo.setText("");
        Tdescripcion.setText("");
        Tcantidad.setText("");
        Tprecio.setText("");
    }//GEN-LAST:event_BmodificarActionPerformed

    private void BreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreporteActionPerformed
        Reporte ventana2 = new Reporte();
        ventana2.setBounds(465, 200, 480, 450);
        ventana2.setVisible(true);
    }//GEN-LAST:event_BreporteActionPerformed

    public void Agregar(){
        String mensaje;
        if (activo == true)
            mensaje = Rsi.getText();
        else 
            mensaje = Rno.getText();
        tabla.addRow(new Object[]{Tcodigo.getText(), Tdescripcion.getText(), Tcantidad.getText(), Combo.getSelectedItem(), mensaje, Tprecio.getText()});
        Tcodigo.setText("");
        Tdescripcion.setText("");
        Tcantidad.setText("");
        Tprecio.setText("");
    }
    
       public void ConsultaActivo() {
        if (Rsi.isSelected()) {
            activo = true;
        } else if (Rno.isSelected()) {
            activo = false;
        }
    }
    
        public void Borrar(){
        int indice = Tacontrol.getSelectedRow();
        tabla.removeRow(indice);
        }
        
         public void Modificar(){
        int indice = Tacontrol.getSelectedRow();
        tabla.setValueAt(Tcodigo.getText(), indice, 0);
        tabla.setValueAt(Tdescripcion.getText(), indice, 1);
        tabla.setValueAt(Tcantidad.getText(), indice, 2);
        tabla.setValueAt(Combo.getSelectedItem(), indice, 3);
        ConsultaActivo();
        String mensaje;
        if (activo == true){
            mensaje = Rsi.getText();}
         else
            mensaje = Rno.getText();
        tabla.setValueAt(mensaje, indice, 4);
        tabla.setValueAt(Tprecio.getText(), indice, 5);
    }
         
        public void Guardar(){
        FileWriter archivo = null;
        PrintWriter pw = null;
        
        try {
            archivo = new FileWriter("C:\\temp\\articulo\\" + Tcodigo.getText() + ".txt");
            pw = new PrintWriter(archivo);
            pw.println("Codigo: " + Tcodigo.getText());
            pw.println("Descripcion: " + Tdescripcion.getText());
            pw.println("Cantidad: " + Tcantidad.getText());
            pw.println("Tipo: " + Combo.getSelectedItem());
            pw.println("Precio: " + Tprecio.getText());

        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            try {
                if (archivo!=null) {
                    archivo.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagregar;
    private javax.swing.JButton Bborrar;
    private javax.swing.JButton Bmodificar;
    private javax.swing.JButton Breporte;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JRadioButton Rno;
    private javax.swing.JRadioButton Rsi;
    private javax.swing.JTable Tacontrol;
    private javax.swing.JTextField Tcantidad;
    private javax.swing.JTextField Tcodigo;
    private javax.swing.JTextField Tdescripcion;
    private javax.swing.JTextField Tprecio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
